//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoExterno.ReferenciaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutenticarDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class AutenticarDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((this.EmpleadoField.Equals(value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sesion {
            get {
                return this.SesionField;
            }
            set {
                if ((this.SesionField.Equals(value) != true)) {
                    this.SesionField = value;
                    this.RaisePropertyChanged("Sesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((this.UsuarioField.Equals(value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OPDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class OPDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HermanadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupervisorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hermanado {
            get {
                return this.HermanadoField;
            }
            set {
                if ((this.HermanadoField.Equals(value) != true)) {
                    this.HermanadoField = value;
                    this.RaisePropertyChanged("Hermanado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Linea {
            get {
                return this.LineaField;
            }
            set {
                if ((this.LineaField.Equals(value) != true)) {
                    this.LineaField = value;
                    this.RaisePropertyChanged("Linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((this.ModeloField.Equals(value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Supervisor {
            get {
                return this.SupervisorField;
            }
            set {
                if ((this.SupervisorField.Equals(value) != true)) {
                    this.SupervisorField = value;
                    this.RaisePropertyChanged("Supervisor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class ModeloDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenominacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ObjetivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SKUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denominacion {
            get {
                return this.DenominacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DenominacionField, value) != true)) {
                    this.DenominacionField = value;
                    this.RaisePropertyChanged("Denominacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Objetivo {
            get {
                return this.ObjetivoField;
            }
            set {
                if ((this.ObjetivoField.Equals(value) != true)) {
                    this.ObjetivoField = value;
                    this.RaisePropertyChanged("Objetivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((this.SKUField.Equals(value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class ColorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaTrabajoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class LineaTrabajoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDefectoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class TipoDefectoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefectoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class DefectoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDefectoCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDefectoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDefectoTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pie {
            get {
                return this.PieField;
            }
            set {
                if ((object.ReferenceEquals(this.PieField, value) != true)) {
                    this.PieField = value;
                    this.RaisePropertyChanged("Pie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDefectoCodigo {
            get {
                return this.TipoDefectoCodigoField;
            }
            set {
                if ((this.TipoDefectoCodigoField.Equals(value) != true)) {
                    this.TipoDefectoCodigoField = value;
                    this.RaisePropertyChanged("TipoDefectoCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDefectoDescripcion {
            get {
                return this.TipoDefectoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDefectoDescripcionField, value) != true)) {
                    this.TipoDefectoDescripcionField = value;
                    this.RaisePropertyChanged("TipoDefectoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDefectoTipo {
            get {
                return this.TipoDefectoTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDefectoTipoField, value) != true)) {
                    this.TipoDefectoTipoField = value;
                    this.RaisePropertyChanged("TipoDefectoTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InspeccionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class InspeccionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaYHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AccesoExterno.ReferenciaServicio.DefectoDTO[] ListaDefectosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaYHora {
            get {
                return this.FechaYHoraField;
            }
            set {
                if ((this.FechaYHoraField.Equals(value) != true)) {
                    this.FechaYHoraField = value;
                    this.RaisePropertyChanged("FechaYHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccesoExterno.ReferenciaServicio.DefectoDTO[] ListaDefectos {
            get {
                return this.ListaDefectosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaDefectosField, value) != true)) {
                    this.ListaDefectosField = value;
                    this.RaisePropertyChanged("ListaDefectos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicio.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Autenticar", ReplyAction="http://tempuri.org/IServicio/AutenticarResponse")]
        AccesoExterno.ReferenciaServicio.AutenticarDTO Autenticar(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Autenticar", ReplyAction="http://tempuri.org/IServicio/AutenticarResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.AutenticarDTO> AutenticarAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CerrarSesion", ReplyAction="http://tempuri.org/IServicio/CerrarSesionResponse")]
        bool CerrarSesion(int sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CerrarSesion", ReplyAction="http://tempuri.org/IServicio/CerrarSesionResponse")]
        System.Threading.Tasks.Task<bool> CerrarSesionAsync(int sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarOPs", ReplyAction="http://tempuri.org/IServicio/ListarOPsResponse")]
        AccesoExterno.ReferenciaServicio.OPDTO[] ListarOPs(int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarOPs", ReplyAction="http://tempuri.org/IServicio/ListarOPsResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.OPDTO[]> ListarOPsAsync(int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ReanudarOP", ReplyAction="http://tempuri.org/IServicio/ReanudarOPResponse")]
        bool ReanudarOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ReanudarOP", ReplyAction="http://tempuri.org/IServicio/ReanudarOPResponse")]
        System.Threading.Tasks.Task<bool> ReanudarOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/FinalizarOP", ReplyAction="http://tempuri.org/IServicio/FinalizarOPResponse")]
        bool FinalizarOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/FinalizarOP", ReplyAction="http://tempuri.org/IServicio/FinalizarOPResponse")]
        System.Threading.Tasks.Task<bool> FinalizarOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PausarOP", ReplyAction="http://tempuri.org/IServicio/PausarOPResponse")]
        bool PausarOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PausarOP", ReplyAction="http://tempuri.org/IServicio/PausarOPResponse")]
        System.Threading.Tasks.Task<bool> PausarOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetModelos", ReplyAction="http://tempuri.org/IServicio/GetModelosResponse")]
        AccesoExterno.ReferenciaServicio.ModeloDTO[] GetModelos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetModelos", ReplyAction="http://tempuri.org/IServicio/GetModelosResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.ModeloDTO[]> GetModelosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetColores", ReplyAction="http://tempuri.org/IServicio/GetColoresResponse")]
        AccesoExterno.ReferenciaServicio.ColorDTO[] GetColores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetColores", ReplyAction="http://tempuri.org/IServicio/GetColoresResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.ColorDTO[]> GetColoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetLineasLibres", ReplyAction="http://tempuri.org/IServicio/GetLineasLibresResponse")]
        AccesoExterno.ReferenciaServicio.LineaTrabajoDTO[] GetLineasLibres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetLineasLibres", ReplyAction="http://tempuri.org/IServicio/GetLineasLibresResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.LineaTrabajoDTO[]> GetLineasLibresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ControlarOPsTodasFinalizadas", ReplyAction="http://tempuri.org/IServicio/ControlarOPsTodasFinalizadasResponse")]
        bool ControlarOPsTodasFinalizadas(int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ControlarOPsTodasFinalizadas", ReplyAction="http://tempuri.org/IServicio/ControlarOPsTodasFinalizadasResponse")]
        System.Threading.Tasks.Task<bool> ControlarOPsTodasFinalizadasAsync(int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/IniciarOP", ReplyAction="http://tempuri.org/IServicio/IniciarOPResponse")]
        bool IniciarOP(int numero, int linea, int modelo, int color, int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/IniciarOP", ReplyAction="http://tempuri.org/IServicio/IniciarOPResponse")]
        System.Threading.Tasks.Task<bool> IniciarOPAsync(int numero, int linea, int modelo, int color, int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListaOPs", ReplyAction="http://tempuri.org/IServicio/ListaOPsResponse")]
        AccesoExterno.ReferenciaServicio.OPDTO[] ListaOPs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListaOPs", ReplyAction="http://tempuri.org/IServicio/ListaOPsResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.OPDTO[]> ListaOPsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AptoCargarHermanado", ReplyAction="http://tempuri.org/IServicio/AptoCargarHermanadoResponse")]
        bool AptoCargarHermanado(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AptoCargarHermanado", ReplyAction="http://tempuri.org/IServicio/AptoCargarHermanadoResponse")]
        System.Threading.Tasks.Task<bool> AptoCargarHermanadoAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetOP", ReplyAction="http://tempuri.org/IServicio/GetOPResponse")]
        AccesoExterno.ReferenciaServicio.OPDTO GetOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetOP", ReplyAction="http://tempuri.org/IServicio/GetOPResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.OPDTO> GetOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CargarHermanado", ReplyAction="http://tempuri.org/IServicio/CargarHermanadoResponse")]
        bool CargarHermanado(int hermanado, int op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CargarHermanado", ReplyAction="http://tempuri.org/IServicio/CargarHermanadoResponse")]
        System.Threading.Tasks.Task<bool> CargarHermanadoAsync(int hermanado, int op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AsociarOP", ReplyAction="http://tempuri.org/IServicio/AsociarOPResponse")]
        int AsociarOP(int numero, int supervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AsociarOP", ReplyAction="http://tempuri.org/IServicio/AsociarOPResponse")]
        System.Threading.Tasks.Task<int> AsociarOPAsync(int numero, int supervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoDefectos", ReplyAction="http://tempuri.org/IServicio/ListarTipoDefectosResponse")]
        AccesoExterno.ReferenciaServicio.TipoDefectoDTO[] ListarTipoDefectos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTipoDefectos", ReplyAction="http://tempuri.org/IServicio/ListarTipoDefectosResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.TipoDefectoDTO[]> ListarTipoDefectosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistrarInspeccion", ReplyAction="http://tempuri.org/IServicio/RegistrarInspeccionResponse")]
        int RegistrarInspeccion(int numeroOP, AccesoExterno.ReferenciaServicio.DefectoDTO[] defectos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistrarInspeccion", ReplyAction="http://tempuri.org/IServicio/RegistrarInspeccionResponse")]
        System.Threading.Tasks.Task<int> RegistrarInspeccionAsync(int numeroOP, AccesoExterno.ReferenciaServicio.DefectoDTO[] defectos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DesasociarOP", ReplyAction="http://tempuri.org/IServicio/DesasociarOPResponse")]
        bool DesasociarOP(int numeroOP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DesasociarOP", ReplyAction="http://tempuri.org/IServicio/DesasociarOPResponse")]
        System.Threading.Tasks.Task<bool> DesasociarOPAsync(int numeroOP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetInspeccion", ReplyAction="http://tempuri.org/IServicio/GetInspeccionResponse")]
        AccesoExterno.ReferenciaServicio.InspeccionDTO GetInspeccion(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetInspeccion", ReplyAction="http://tempuri.org/IServicio/GetInspeccionResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.InspeccionDTO> GetInspeccionAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetDefecto", ReplyAction="http://tempuri.org/IServicio/GetDefectoResponse")]
        AccesoExterno.ReferenciaServicio.DefectoDTO GetDefecto(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetDefecto", ReplyAction="http://tempuri.org/IServicio/GetDefectoResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.DefectoDTO> GetDefectoAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : AccesoExterno.ReferenciaServicio.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<AccesoExterno.ReferenciaServicio.IServicio>, AccesoExterno.ReferenciaServicio.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AccesoExterno.ReferenciaServicio.AutenticarDTO Autenticar(string user, string pass) {
            return base.Channel.Autenticar(user, pass);
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.AutenticarDTO> AutenticarAsync(string user, string pass) {
            return base.Channel.AutenticarAsync(user, pass);
        }
        
        public bool CerrarSesion(int sesion) {
            return base.Channel.CerrarSesion(sesion);
        }
        
        public System.Threading.Tasks.Task<bool> CerrarSesionAsync(int sesion) {
            return base.Channel.CerrarSesionAsync(sesion);
        }
        
        public AccesoExterno.ReferenciaServicio.OPDTO[] ListarOPs(int empleado) {
            return base.Channel.ListarOPs(empleado);
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.OPDTO[]> ListarOPsAsync(int empleado) {
            return base.Channel.ListarOPsAsync(empleado);
        }
        
        public bool ReanudarOP(int numero) {
            return base.Channel.ReanudarOP(numero);
        }
        
        public System.Threading.Tasks.Task<bool> ReanudarOPAsync(int numero) {
            return base.Channel.ReanudarOPAsync(numero);
        }
        
        public bool FinalizarOP(int numero) {
            return base.Channel.FinalizarOP(numero);
        }
        
        public System.Threading.Tasks.Task<bool> FinalizarOPAsync(int numero) {
            return base.Channel.FinalizarOPAsync(numero);
        }
        
        public bool PausarOP(int numero) {
            return base.Channel.PausarOP(numero);
        }
        
        public System.Threading.Tasks.Task<bool> PausarOPAsync(int numero) {
            return base.Channel.PausarOPAsync(numero);
        }
        
        public AccesoExterno.ReferenciaServicio.ModeloDTO[] GetModelos() {
            return base.Channel.GetModelos();
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.ModeloDTO[]> GetModelosAsync() {
            return base.Channel.GetModelosAsync();
        }
        
        public AccesoExterno.ReferenciaServicio.ColorDTO[] GetColores() {
            return base.Channel.GetColores();
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.ColorDTO[]> GetColoresAsync() {
            return base.Channel.GetColoresAsync();
        }
        
        public AccesoExterno.ReferenciaServicio.LineaTrabajoDTO[] GetLineasLibres() {
            return base.Channel.GetLineasLibres();
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.LineaTrabajoDTO[]> GetLineasLibresAsync() {
            return base.Channel.GetLineasLibresAsync();
        }
        
        public bool ControlarOPsTodasFinalizadas(int empleado) {
            return base.Channel.ControlarOPsTodasFinalizadas(empleado);
        }
        
        public System.Threading.Tasks.Task<bool> ControlarOPsTodasFinalizadasAsync(int empleado) {
            return base.Channel.ControlarOPsTodasFinalizadasAsync(empleado);
        }
        
        public bool IniciarOP(int numero, int linea, int modelo, int color, int empleado) {
            return base.Channel.IniciarOP(numero, linea, modelo, color, empleado);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarOPAsync(int numero, int linea, int modelo, int color, int empleado) {
            return base.Channel.IniciarOPAsync(numero, linea, modelo, color, empleado);
        }
        
        public AccesoExterno.ReferenciaServicio.OPDTO[] ListaOPs() {
            return base.Channel.ListaOPs();
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.OPDTO[]> ListaOPsAsync() {
            return base.Channel.ListaOPsAsync();
        }
        
        public bool AptoCargarHermanado(int numero) {
            return base.Channel.AptoCargarHermanado(numero);
        }
        
        public System.Threading.Tasks.Task<bool> AptoCargarHermanadoAsync(int numero) {
            return base.Channel.AptoCargarHermanadoAsync(numero);
        }
        
        public AccesoExterno.ReferenciaServicio.OPDTO GetOP(int numero) {
            return base.Channel.GetOP(numero);
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.OPDTO> GetOPAsync(int numero) {
            return base.Channel.GetOPAsync(numero);
        }
        
        public bool CargarHermanado(int hermanado, int op) {
            return base.Channel.CargarHermanado(hermanado, op);
        }
        
        public System.Threading.Tasks.Task<bool> CargarHermanadoAsync(int hermanado, int op) {
            return base.Channel.CargarHermanadoAsync(hermanado, op);
        }
        
        public int AsociarOP(int numero, int supervisor) {
            return base.Channel.AsociarOP(numero, supervisor);
        }
        
        public System.Threading.Tasks.Task<int> AsociarOPAsync(int numero, int supervisor) {
            return base.Channel.AsociarOPAsync(numero, supervisor);
        }
        
        public AccesoExterno.ReferenciaServicio.TipoDefectoDTO[] ListarTipoDefectos() {
            return base.Channel.ListarTipoDefectos();
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.TipoDefectoDTO[]> ListarTipoDefectosAsync() {
            return base.Channel.ListarTipoDefectosAsync();
        }
        
        public int RegistrarInspeccion(int numeroOP, AccesoExterno.ReferenciaServicio.DefectoDTO[] defectos) {
            return base.Channel.RegistrarInspeccion(numeroOP, defectos);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarInspeccionAsync(int numeroOP, AccesoExterno.ReferenciaServicio.DefectoDTO[] defectos) {
            return base.Channel.RegistrarInspeccionAsync(numeroOP, defectos);
        }
        
        public bool DesasociarOP(int numeroOP) {
            return base.Channel.DesasociarOP(numeroOP);
        }
        
        public System.Threading.Tasks.Task<bool> DesasociarOPAsync(int numeroOP) {
            return base.Channel.DesasociarOPAsync(numeroOP);
        }
        
        public AccesoExterno.ReferenciaServicio.InspeccionDTO GetInspeccion(int codigo) {
            return base.Channel.GetInspeccion(codigo);
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.InspeccionDTO> GetInspeccionAsync(int codigo) {
            return base.Channel.GetInspeccionAsync(codigo);
        }
        
        public AccesoExterno.ReferenciaServicio.DefectoDTO GetDefecto(int codigo) {
            return base.Channel.GetDefecto(codigo);
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.DefectoDTO> GetDefectoAsync(int codigo) {
            return base.Channel.GetDefectoAsync(codigo);
        }
    }
}
