//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoExterno.ReferenciaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutenticarDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class AutenticarDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((this.EmpleadoField.Equals(value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sesion {
            get {
                return this.SesionField;
            }
            set {
                if ((this.SesionField.Equals(value) != true)) {
                    this.SesionField = value;
                    this.RaisePropertyChanged("Sesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((this.UsuarioField.Equals(value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OPDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class OPDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HermanadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupervisorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hermanado {
            get {
                return this.HermanadoField;
            }
            set {
                if ((this.HermanadoField.Equals(value) != true)) {
                    this.HermanadoField = value;
                    this.RaisePropertyChanged("Hermanado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Linea {
            get {
                return this.LineaField;
            }
            set {
                if ((this.LineaField.Equals(value) != true)) {
                    this.LineaField = value;
                    this.RaisePropertyChanged("Linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((this.ModeloField.Equals(value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Supervisor {
            get {
                return this.SupervisorField;
            }
            set {
                if ((this.SupervisorField.Equals(value) != true)) {
                    this.SupervisorField = value;
                    this.RaisePropertyChanged("Supervisor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class ModeloDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenominacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ObjetivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SKUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denominacion {
            get {
                return this.DenominacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DenominacionField, value) != true)) {
                    this.DenominacionField = value;
                    this.RaisePropertyChanged("Denominacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Objetivo {
            get {
                return this.ObjetivoField;
            }
            set {
                if ((this.ObjetivoField.Equals(value) != true)) {
                    this.ObjetivoField = value;
                    this.RaisePropertyChanged("Objetivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((this.SKUField.Equals(value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class ColorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaTrabajoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Entidades")]
    [System.SerializableAttribute()]
    public partial class LineaTrabajoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicio.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Autenticar", ReplyAction="http://tempuri.org/IServicio/AutenticarResponse")]
        AccesoExterno.ReferenciaServicio.AutenticarDTO Autenticar(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/Autenticar", ReplyAction="http://tempuri.org/IServicio/AutenticarResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.AutenticarDTO> AutenticarAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CerrarSesion", ReplyAction="http://tempuri.org/IServicio/CerrarSesionResponse")]
        bool CerrarSesion(int sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CerrarSesion", ReplyAction="http://tempuri.org/IServicio/CerrarSesionResponse")]
        System.Threading.Tasks.Task<bool> CerrarSesionAsync(int sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarOPs", ReplyAction="http://tempuri.org/IServicio/ListarOPsResponse")]
        AccesoExterno.ReferenciaServicio.OPDTO[] ListarOPs(int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarOPs", ReplyAction="http://tempuri.org/IServicio/ListarOPsResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.OPDTO[]> ListarOPsAsync(int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ReanudarOP", ReplyAction="http://tempuri.org/IServicio/ReanudarOPResponse")]
        bool ReanudarOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ReanudarOP", ReplyAction="http://tempuri.org/IServicio/ReanudarOPResponse")]
        System.Threading.Tasks.Task<bool> ReanudarOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/FinalizarOP", ReplyAction="http://tempuri.org/IServicio/FinalizarOPResponse")]
        bool FinalizarOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/FinalizarOP", ReplyAction="http://tempuri.org/IServicio/FinalizarOPResponse")]
        System.Threading.Tasks.Task<bool> FinalizarOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PausarOP", ReplyAction="http://tempuri.org/IServicio/PausarOPResponse")]
        bool PausarOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/PausarOP", ReplyAction="http://tempuri.org/IServicio/PausarOPResponse")]
        System.Threading.Tasks.Task<bool> PausarOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetModelos", ReplyAction="http://tempuri.org/IServicio/GetModelosResponse")]
        AccesoExterno.ReferenciaServicio.ModeloDTO[] GetModelos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetModelos", ReplyAction="http://tempuri.org/IServicio/GetModelosResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.ModeloDTO[]> GetModelosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetColores", ReplyAction="http://tempuri.org/IServicio/GetColoresResponse")]
        AccesoExterno.ReferenciaServicio.ColorDTO[] GetColores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetColores", ReplyAction="http://tempuri.org/IServicio/GetColoresResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.ColorDTO[]> GetColoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetLineasLibres", ReplyAction="http://tempuri.org/IServicio/GetLineasLibresResponse")]
        AccesoExterno.ReferenciaServicio.LineaTrabajoDTO[] GetLineasLibres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetLineasLibres", ReplyAction="http://tempuri.org/IServicio/GetLineasLibresResponse")]
        System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.LineaTrabajoDTO[]> GetLineasLibresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ControlarOPsTodasFinalizadas", ReplyAction="http://tempuri.org/IServicio/ControlarOPsTodasFinalizadasResponse")]
        bool ControlarOPsTodasFinalizadas(int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ControlarOPsTodasFinalizadas", ReplyAction="http://tempuri.org/IServicio/ControlarOPsTodasFinalizadasResponse")]
        System.Threading.Tasks.Task<bool> ControlarOPsTodasFinalizadasAsync(int empleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : AccesoExterno.ReferenciaServicio.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<AccesoExterno.ReferenciaServicio.IServicio>, AccesoExterno.ReferenciaServicio.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AccesoExterno.ReferenciaServicio.AutenticarDTO Autenticar(string user, string pass) {
            return base.Channel.Autenticar(user, pass);
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.AutenticarDTO> AutenticarAsync(string user, string pass) {
            return base.Channel.AutenticarAsync(user, pass);
        }
        
        public bool CerrarSesion(int sesion) {
            return base.Channel.CerrarSesion(sesion);
        }
        
        public System.Threading.Tasks.Task<bool> CerrarSesionAsync(int sesion) {
            return base.Channel.CerrarSesionAsync(sesion);
        }
        
        public AccesoExterno.ReferenciaServicio.OPDTO[] ListarOPs(int empleado) {
            return base.Channel.ListarOPs(empleado);
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.OPDTO[]> ListarOPsAsync(int empleado) {
            return base.Channel.ListarOPsAsync(empleado);
        }
        
        public bool ReanudarOP(int numero) {
            return base.Channel.ReanudarOP(numero);
        }
        
        public System.Threading.Tasks.Task<bool> ReanudarOPAsync(int numero) {
            return base.Channel.ReanudarOPAsync(numero);
        }
        
        public bool FinalizarOP(int numero) {
            return base.Channel.FinalizarOP(numero);
        }
        
        public System.Threading.Tasks.Task<bool> FinalizarOPAsync(int numero) {
            return base.Channel.FinalizarOPAsync(numero);
        }
        
        public bool PausarOP(int numero) {
            return base.Channel.PausarOP(numero);
        }
        
        public System.Threading.Tasks.Task<bool> PausarOPAsync(int numero) {
            return base.Channel.PausarOPAsync(numero);
        }
        
        public AccesoExterno.ReferenciaServicio.ModeloDTO[] GetModelos() {
            return base.Channel.GetModelos();
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.ModeloDTO[]> GetModelosAsync() {
            return base.Channel.GetModelosAsync();
        }
        
        public AccesoExterno.ReferenciaServicio.ColorDTO[] GetColores() {
            return base.Channel.GetColores();
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.ColorDTO[]> GetColoresAsync() {
            return base.Channel.GetColoresAsync();
        }
        
        public AccesoExterno.ReferenciaServicio.LineaTrabajoDTO[] GetLineasLibres() {
            return base.Channel.GetLineasLibres();
        }
        
        public System.Threading.Tasks.Task<AccesoExterno.ReferenciaServicio.LineaTrabajoDTO[]> GetLineasLibresAsync() {
            return base.Channel.GetLineasLibresAsync();
        }
        
        public bool ControlarOPsTodasFinalizadas(int empleado) {
            return base.Channel.ControlarOPsTodasFinalizadas(empleado);
        }
        
        public System.Threading.Tasks.Task<bool> ControlarOPsTodasFinalizadasAsync(int empleado) {
            return base.Channel.ControlarOPsTodasFinalizadasAsync(empleado);
        }
    }
}
